CREATE TABLE IF NOT EXISTS `trade_bills` (
  `bill_id` int(11) NOT NULL AUTO_INCREMENT COMMENT '取引ID',
  `related_bill_id` int(11) NOT NULL COMMENT '関連取引ID',
  `bill_name` varchar(200) COLLATE utf8_unicode_ci NOT NULL COMMENT '取引名称',
  `type_id` int(11) NOT NULL COMMENT '取引種別ID',
  `worker_operator_id` int(11) NOT NULL COMMENT '受注担当者ID',
  `customer_operator_id` int(11) NOT NULL COMMENT '発注担当者ID',
  `price_rate` int(11) NOT NULL COMMENT '案件全体に対する金額の比率',
  `subtotal` int(11) NOT NULL COMMENT '小計',
  `discount` int(11) NOT NULL COMMENT '割引金額',
  `tax` int(11) NOT NULL COMMENT '消費税',
  `total` int(11) NOT NULL COMMENT '合計金額',
  `adjust_title` varchar(100) COLLATE utf8_unicode_ci NOT NULL COMMENT '調整タイトル',
  `adjust` int(11) NOT NULL COMMENT '調整金額',
  `payment_total` int(11) NOT NULL COMMENT '入金予定金額',
  `payed_total` int(11) NOT NULL COMMENT '入金済み金額',
  `quotation_date` date DEFAULT NULL COMMENT '見積書発行日',
  `ordered_date` date DEFAULT NULL COMMENT '受注日',
  `deliver_date` date NOT NULL COMMENT '納品予定日',
  `delivered_date` date DEFAULT NULL COMMENT '納品日',
  `billing_date` date DEFAULT NULL COMMENT '請求書発行日',
  `payment_date` date DEFAULT NULL COMMENT '支払い期限日',
  `complete_date` date DEFAULT NULL COMMENT '入金確認日',
  `status_id` int(11) NOT NULL COMMENT '取引ステータス',
  `continue_interval` int(1) NOT NULL COMMENT '継続案件発行間隔月数',
  `description` varchar(8192) COLLATE utf8_unicode_ci NOT NULL COMMENT '特記事項',
  `comment` varchar(8192) COLLATE utf8_unicode_ci NOT NULL COMMENT '備考',
  `create_time` datetime NOT NULL COMMENT 'データ登録日時',
  `update_time` datetime NOT NULL COMMENT 'データ最終更新日時',
  PRIMARY KEY (`bill_id`),
  KEY `related_trade_id` (`related_bill_id`),
  KEY `worker_operator_id` (`worker_operator_id`),
  KEY `customer_operator_id` (`customer_operator_id`),
  KEY `trade_type_id` (`type_id`),
  KEY `trade_status_id` (`status_id`),
  KEY `start_date` (`start_date`),
  KEY `ordered_date` (`ordered_date`),
  KEY `planed_date` (`planed_date`),
  KEY `delivered_date` (`delivered_date`),
  KEY `billing_date` (`billing_date`),
  KEY `payment_date` (`payment_date`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='請求テーブル';

ALTER TABLE `trade_bills`
  ADD CONSTRAINT `trade_bills_ibfk_1` FOREIGN KEY (`type_id`) REFERENCES `trade_types` (`type_id`),
  ADD CONSTRAINT `trade_bills_ibfk_2` FOREIGN KEY (`worker_operator_id`) REFERENCES `admin_company_operators` (`operator_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `trade_bills_ibfk_3` FOREIGN KEY (`customer_operator_id`) REFERENCES `admin_company_operators` (`operator_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `trade_bills_ibfk_4` FOREIGN KEY (`status_id`) REFERENCES `trade_statuses` (`status_id`);
